export const customFontsFromTheInternet = ['mass_effect_123regular']
export const googleFonts = ['Roboto', 'Open Sans', 'Noto Sans JP', 'Lato', 'Montserrat', 'Source Sans Pro', 'Roboto Condensed', 'Poppins', 'Oswald', 'Noto Sans', 'Roboto Mono', 'Raleway', 'Merriweather', 'Nunito', 'Ubuntu', 'PT Sans', 'Roboto Slab', 'Playfair Display', 'Open Sans Condensed', 'Rubik', 'Lora', 'Noto Sans KR', 'Work Sans', 'Mukta', 'Hind Siliguri', 'Nanum Gothic', 'Nunito Sans', 'Inter', 'Quicksand', 'Fira Sans', 'PT Serif', 'Titillium Web', 'Noto Serif', 'Noto Sans TC', 'Karla', 'Heebo', 'Barlow', 'Inconsolata', 'Libre Franklin', 'Dosis', 'Mulish', 'Arimo', 'Oxygen', 'PT Sans Narrow', 'Source Code Pro', 'Josefin Sans', 'Anton', 'Libre Baskerville', 'Bebas Neue', 'Bitter', 'Cabin', 'Crimson Text', 'IBM Plex Sans', 'Dancing Script', 'Hind', 'Yanull Kaffeesatz', 'Prompt', 'Cairo', 'Fjalla One', 'Lobster', 'Source Serif Pro', 'Teko', 'DM Sans', 'Varela Round', 'Abel', 'Barlow Condensed', 'Arvo', 'Comfortaa', 'EB Garamond', 'Kanit', 'Zilla Slab', 'Pacifico', 'Noto Sans SC', 'Exo 2', 'Indie Flower', 'Merriweather Sans', 'Shadows Into Light', 'Noto Serif JP', 'Assistant', 'Asap', 'Overpass', 'Abril Fatface', 'Padauk', 'Questrial', 'Rajdhani', 'Maven Pro', 'Cormorant Garamond', 'Barlow Semi Condensed', 'Hind Madurai', 'Martel', 'Exo', 'Slabo 27px', 'IBM Plex Serif', 'Signika Negative', 'Archivo Narrow', 'Catamaran', 'Fira Sans Condensed', 'Manrope', 'Tajawal', 'Acme', 'Caveat', 'Righteous', 'Domine', 'Amatic SC', 'Play', 'Nanum Myeongjo', 'Bree Serif', 'M PLUS Rounded 1c', 'Secular One', 'Sarabun', 'Staatliches', 'Signika', 'Antic Slab', 'Spartan', 'Architects Daughter', 'Patrick Hand', 'Almarai', 'Alfa Slab One', 'Vollkorn', 'Archivo', 'Satisfy', 'Cinzel', 'ABeeZee', 'Crete Round', 'M PLUS 1p', 'Amiri', 'Fredoka One', 'Alegreya Sans', 'Patua One', 'Public Sans', 'Permanent Marker', 'Gothic A1', 'Courgette', 'Jost', 'Ubuntu Condensed', 'Kaushan Script', 'Tinos', 'Alegreya', 'Lobster Two', 'Noto Sans HK', 'Hammersmith One', 'PT Sans Caption', 'Balsamiq Sans', 'Great Vibes', 'Bangers', 'Frank Ruhl Libre', 'Red Hat Display', 'Archivo Black', 'Merienda', 'Spectral', 'IBM Plex Mono', 'Yantramanav', 'Didact Gothic', 'Luckiest Guy', 'Cardo', 'Prata', 'Parisienne', 'Monda', 'Baloo 2', 'Chakra Petch', 'Saira Condensed', 'Russo One', 'Cuprum', 'Marcellus', 'Francois One', 'Kalam', 'Orbitron', 'Noticia Text', 'Quattrocento Sans', 'DM Serif Display', 'Ropa Sans', 'Concert One', 'Sacramento', 'Old Standard TT', 'Encode Sans', 'Rokkitt', 'Gloria Hallelujah', 'Volkhov', 'Cantarell', 'Special Elite', 'Pathway Gothic One', 'Noto Serif TC', 'Passion One', 'Josefin Slab', 'News Cycle', 'Playfair Display SC', 'Chivo', 'Unna', 'Yellowtail', 'Sawarabi Mincho', 'Sigmar One', 'Changa', 'Cormorant', 'Quattrocento', 'Poiret One', 'Cookie', 'Mate SC', 'Faustina', 'Asap Condensed', 'Neuton', 'Karma', 'Sanchez', 'Press Start 2P', 'Taviraj', 'Crimson Pro', 'Oleo Script', 'Advent Pro', 'Montserrat Alternates', 'Khand', 'Space Mono', 'Vidaloka', 'Philosopher', 'Economica', 'Tangerine', 'Istok Web', 'Playball', 'Monoton', 'PT Mono', 'Ultra', 'Neucha', 'Fira Sans Extra Condensed', 'Mitr', 'Handlee', 'Bai Jamjuree', 'Saira', 'Hind Vadodara', 'Alata', 'Arapey', 'Ubuntu Mono', 'Gudea', 'BenchNine', 'Viga', 'Carter One', 'Cabin Condensed', 'Sawarabi Gothic', 'Rock Salt', 'Gelasio', 'Gentium Basic', 'Ruda', 'Alice', 'Saira Semi Condensed', 'Homemade Apple', 'Jura', 'El Messiri', 'Actor', 'Unica One', 'Allura', 'Amaranth', 'Yeseva One', 'Paytone One', 'Pragati Narrow', 'Lusitana', 'Recursive', 'Khula', 'Armata', 'Julius Sans One', 'Adamina', 'Mandali', 'DM Serif Text', 'Mali', 'Aleo', 'Kosugi Maru', 'Nanum Gothic Coding', 'Marck Script', 'Gochi Hand', 'Noto Serif KR', 'Bad Script', 'Abhaya Libre', 'Squada One', 'Pontano Sans', 'Electrolize', 'Markazi Text', 'Nanum Pen Script', 'Gentium Book Basic', 'Sarala', 'Palanquin', 'Alef', 'Arima Madurai', 'Knewave', 'Red Hat Text', 'Alex Brush', 'Noto Serif SC', 'Nothing You Could Do', 'Gruppo', 'Martel Sans', 'Jaldi', 'Ramabhadra', 'Pangolin', 'Mr Dafoe', 'Rufina', 'Lexend Deca', 'Tenor Sans', 'Sorts Mill Goudy', 'Quantico', 'Shadows Into Light Two', 'Basic', 'Sen', 'Bungee', 'Fugaz One', 'Damion', 'Cousine', 'Aclonica', 'Mate', 'Syncopate', 'Audiowide', 'Pridi', 'Itim', 'Share Tech Mono', 'Black Ops One', 'Courier Prime', 'Suez One', 'Average', 'Allerta', 'Voltaire', 'Rancho', 'Lilita One', 'Hind Guntur', 'Changa One', 'Varela', 'Yrsa', 'Cantata One', 'Berkshire Swash', 'Glegoo', 'Encode Sans Condensed', 'Fira Mono', 'Candal', 'Arsenal', 'Pinyon Script', 'Alegreya Sans SC', 'Commissioner', 'Niconne', 'Sriracha', 'Fredericka the Great', 'Shrikhand', 'Reem Kufi', 'Literata', 'Baloo Tamma 2', 'Six Caps', 'Krub', 'Michroma', 'Sintony', 'Chewy', 'Mukta Malar', 'Spinnaker', 'Kreon', 'Mada', 'Reenie Beanie', 'Italianno', 'Antic', 'Enriqueta', 'Lalezar', 'Coda', 'Days One', 'Black Han Sans', 'Forum', 'Coda Caption', 'Bevan', 'Stint Ultra Condensed', 'Anonymous Pro', 'Laila', 'Overlock', 'Kameron', 'Scheherazade', 'PT Serif Caption', 'Bowlby One SC', 'Covered By Your Grace', 'Trirong', 'VT323', 'Rambla', 'Capriola', 'Bubblegum Sans', 'Allan', 'Caveat Brush', 'Lemonada', 'Convergence', 'Niramit', 'Arizonia', 'Sansita', 'Eczar', 'Cabin Sketch', 'Lateef', 'Rubik Mono One', 'Telex', 'Yesteryear', 'Mukta Vaani', 'Annie Use Your Telescope', 'Racing Sans One', 'Nobile', 'Libre Caslon Text', 'Boogaloo', 'Arbutus Slab', 'Corben', 'Londrina Solid', 'Just Another Hand', 'Aldrich', 'Norican', 'Saira Extra Condensed', 'Rye', 'Castoro', 'Cinzel Decorative', 'Caudex', 'Herr Von Muellerhoff', 'Baloo Tammudu 2', 'Holtwood One SC', 'Biryani', 'Mrs Saint Delafield', 'Ovo', 'Gilda Display', 'Charm', 'Belgrano', 'Molengo', 'Jua', 'Darker Grotesque', 'Judson', 'Pattaya', 'Maitree', 'Kristi', 'Allerta Stencil', 'Miriam Libre', 'Alegreya SC', 'Bungee Inline', 'IBM Plex Sans Condensed', 'Leckerli One', 'Nixie One', 'Rozha One', 'Trocchi', 'Do Hyeon', 'Amita', 'Seaweed Script', 'Coustard', 'Lustria', 'Baloo Thambi 2', 'Epilogue', 'Share', 'Athiti', 'Marcellus SC', 'Suranna', 'Overpass Mono', 'KoHo', 'Nanum Brush Script', 'Comic Neue', 'Coming Soon', 'Scada', 'Delius', 'Titan One', 'Average Sans', 'Belleza', 'Space Grotesk', 'Oranienbaum', 'Rochester', 'Fauna One', 'Magra', 'Carme', 'Graduate', 'Bellefair', 'Krona One', 'Mr De Haviland', 'Contrail One', 'K2D', 'GFS Didot', 'Palanquin Dark', 'Sora', 'Carrois Gothic', 'Chonburi', 'Encode Sans Semi Condensed', 'Merienda One', 'Amiko', 'Jockey One', 'Cedarville Cursive', 'Lexend', 'Grand Hotel', 'Marmelad', 'Slabo 13px', 'Halant', 'La Belle Aurore', 'Baskervville', 'Sunflower', 'Averia Serif Libre', 'Big Shoulders Display', 'Petit Formal Script', 'Wallpoet', 'Rosario', 'Podkova', 'Schoolbell', 'Thasadith', 'Copse', 'Calligraffitti', 'Kosugi', 'Cutive Mono', 'Poly', 'Metrophobic', 'Alatsi', 'Love Ya Like A Sister', 'Be Vietnam', 'Manjari', 'Spectral SC', 'Rammetto One', 'Oxygen Mono', 'Cormorant Infant', 'Radley', 'Averia Libre', 'Kumbh Sans', 'Amethysta', 'Andada', 'Aladin', 'Duru Sans', 'NTR', 'Sniglet', 'Bowlby One', 'Cambay', 'Sofia', 'Lekton', 'Kelly Slab', 'Fira Code', 'IM Fell DW Pica', 'Gugi', 'Marvel', 'Hanuman', 'Mirza', 'Esteban', 'Hi Melody', 'IM Fell English', 'Chelsea Market', 'Cormorant SC', 'Grandstander', 'Harmattan', 'Raleway Dots', 'Megrim', 'Baloo Da 2', 'Bungee Shade', 'IM Fell Double Pica', 'Oleo Script Swash Caps', 'Emilys Candy', 'Balthazar', 'Stardos Stencil', 'Monsieur La Doulaise', 'Gabriela', 'Goudy Bookletter 1911', 'Dawning of a New Day', 'Alike', 'Oregano', 'Bentham', 'Gravitas One', 'ZCOOL XiaoWei', 'Sarpanch', 'Buenard', 'Quando', 'Asar', 'Alike Angular', 'Libre Barcode 39', 'Limelight', 'Rasa', 'Cambo', 'Qwigley', 'JetBrains Mono', 'Creepster', 'David Libre', 'Sue Ellen Francisco', 'Blinker', 'Cutive', 'Kadwa', 'Zeyada', 'Turret Road', 'Waiting for the Sunrise', 'Sedgwick Ave', 'Montez', 'UnifrakturMaguntia', 'Lemon', 'Original Surfer', 'Montaga', 'Skranji', 'Bodoni Moda', 'RocknRoll One', 'Aguafina Script', 'Rouge Script', 'Expletus Sans', 'Brawler', 'Farro', 'Baumans', 'Hepta Slab', 'Newsreader', 'Grenze Gotisch', 'Frijole', 'Baloo Chettan 2', 'B612 Mono', 'Doppio One', 'Proza Libre', 'Finger Paint', 'Battambang', 'Give You Glory', 'Averia Sans Libre', 'Nova Mono', 'Pompiere', 'ZCOOL QingKe HuangYou', 'Anaheim', 'Kurale', 'Ceviche One', 'Galada', 'Fanwood Text', 'Dokdo', 'Happy Monkey', 'BioRhyme', 'Patrick Hand SC', 'Caladea', 'Homenaje', 'Big Shoulders Text', 'Antic Didone', 'Vast Shadow', 'Freckle Face', 'Inder', 'Katibeh', 'Livvic', 'Over the Rainbow', 'Sail', 'Major Mono Display', 'Mallanna', 'Almendra', 'Clicker Script', 'Federo', 'Andika', 'Calistoga', 'Mansalva', 'Share Tech', 'Meddon', 'Gurajada', 'Nova Round', 'Tillana', 'Chau Philomene One', 'Fondamento', 'Faster One', 'Della Respira', 'Mukta Mahee', 'Oxanium', 'Cormorant Upright', 'Numans', 'McLaren', 'Vesper Libre', 'Wendy One', 'Walter Turncoat', 'Ledger', 'Atma', 'Short Stack', 'Rakkas', 'B612', 'Arya', 'Euphoria Script', 'Antonio', 'Aref Ruqaa', 'Vollkorn SC', 'Orienta', 'Yatra One', 'DM Mono', 'Flamenco', 'Inknut Antiqua', 'Mountains of Christmas', 'Goblin One', 'Iceland', 'Poller One', 'Salsa', 'Shojumaru', 'Italiana', 'Unkempt', 'Mako', 'Vampiro One', 'Encode Sans Expanded', 'IM Fell English SC', 'Strait', 'Montserrat Subrayada', 'Timmana', 'Geo', 'Ranga', 'Mouse Memoirs', 'Tenali Ramakrishna', 'Ruslan Display', 'Crafty Girls', 'Medula One', 'Overlock SC', 'Loved by the King', 'Life Savers', 'Bellota Text', 'Tienne', 'Coiny', 'Notable', 'Scope One', 'Codystar', 'Ranchers', 'Peralta', 'Lexend Zetta', 'Cherry Cream Soda', 'Bilbo Swash Caps', 'Meera Inimai', 'Shippori Mincho', 'Delius Swash Caps', 'Carrois Gothic SC', 'Eater', 'Mina', 'Elsie', 'Odibee Sans', 'Gaegu', 'Asul', 'Puritan', 'Artifika', 'The Girl Next Door', 'Dynalight', 'Trade Winds', 'Metamorphous', 'Prosto One', 'Lily Script One', 'Pavanam', 'Georama', 'Wire One', 'Voces', 'Cantora One', 'Imprima', 'Red Rose', 'Gafata', 'Ma Shan Zheng', 'Denk One', 'Yusei Magic', 'Amarante', 'Headland One', 'Charmonman', 'Tauri', 'Yeon Sung', 'Kodchasan', 'Nokora', 'Just Me Again Down Here', 'Nova Square', 'UnifrakturCook', 'Stalemate', 'Delius Unicase', 'Encode Sans Semi Expanded', 'Port Lligat Sans', 'STIX Two Text', 'Bilbo', 'Cherry Swash', 'League Script', 'Fjord One', 'Lovers Quarrel', 'Port Lligat Slab', 'Atkinson Hyperlegible', 'Manuale', 'Saira Stencil One', 'Style Script', 'Goldman', 'Engagement', 'Khmer', 'Song Myung', 'Reggae One', 'Syne', 'Sarina', 'Libre Barcode 39 Text', 'Vibur', 'Sura', 'Cormorant Unicase', 'Mogra', 'New Rocker', 'Hanalei Fill', 'Baloo Bhaina 2', 'Henny Penny', 'Slackey', 'Palette Mosaic', 'Modak', 'Kite One', 'Baloo Paaji 2', 'Fontdiner Swanky', 'Shanti', 'Koulen', 'Paprika', 'Habibi', 'Germania One', 'IM Fell French Canon', 'Fraunces', 'Londrina Outline', 'Gamja Flower', 'Spicy Rice', 'Ribeye', 'Rosarivo', 'Julee', 'Crushed', 'Kranky', 'Jomhuria', 'Prociono', 'IM Fell French Canon SC', 'Chango', 'Cute Font', 'Ramaraja', 'Fresca', 'Rationale', 'Sancreek', 'Milonga', 'Text Me One', 'Bellota', 'Simonetta', 'Dekko', 'Stoke', 'Uncial Antiqua', 'Farsan', 'Kiwi Maru', 'East Sea Dokdo', 'Fahkwang', 'Jolly Lodger', 'Mystery Quest', 'Zilla Slab Highlight', 'Sonsie One', 'Baloo Bhai 2', 'Sulphur Point', 'Dela Gothic One', 'Libre Caslon Display', 'Chicle', 'Quintessential', 'Fenix', 'Donegal One', 'Hahmlet', 'Kulim Park', 'Shippori Mincho B1', 'Bubbler One', 'Lakki Reddy', 'Englebert', 'Kotta One', 'Ruluko', 'Sumana', 'Stint Ultra Expanded', 'Petrona', 'Macondo Swash Caps', 'Akronim', 'Pirata One', 'Bahianita', 'IM Fell Great Primer', 'Solway', 'Cagliostro', 'Sree Krushnadevaraya', 'Moul', 'Ibarra Real Nova', 'Chathura', 'Averia Gruesa Libre', 'Libre Barcode 39 Extended Text', 'Hachi Maru Pop', 'Modern Antiqua', 'Girassol', 'Lexend Exa', 'Trykker', 'Inria Serif', 'Tomorrow', 'Offside', 'Redressed', 'Condiment', 'Kumar One', 'Stylish', 'Nosifer', 'Dorsa', 'Gotu', 'Otomanopee One', 'Buda', 'Swanky and Moo Moo', 'Rowdies', 'Nova Flat', 'Angkor', 'Kavivanar', 'Wellfleet', 'Libre Barcode 128', 'Meie Script', 'DotGothic16', 'Junge', 'Croissant One', 'Margarine', 'Joti One', 'Potta One', 'Inika', 'Jomolhari', 'Monofett', 'Train One', 'Sahitya', 'IM Fell DW Pica SC', 'Piedra', 'Barrio', 'Ravi Prakash', 'Kufam', 'Linden Hill', 'Eagle Lake', 'Maiden Orange', 'Kdam Thmor', 'Barriecito', 'Miniver', 'Sansita Swashed', 'Ruthie', 'Tulpen One', 'Galdeano', 'Marko One', 'Devonshire', 'Arbutus', 'Iceberg', 'MuseoModerno', 'Spirax', 'Autour One', 'Rum Raisin', 'Atomic Age', 'Kantumruy', 'Elsie Swash Caps', 'Felipa', 'Molle', 'Kavoon', 'Sirin Stencil', 'Zen Dots', 'Ribeye Marrow', 'Metal Mania', 'Griffy', 'Bigshot One', 'Bayon', 'Caesar Dressing', 'Srisakdi', 'Mrs Sheppards', 'Content', 'Piazzolla', 'Gayathri', 'Andada Pro', 'Beth Ellen', 'Chilanka', 'Lancelot', 'Rhodium Libre', 'Risque', 'Flavors', 'MonteCarlo', 'Jim Nightshade', 'Londrina Shadow', 'Ewert', 'Bahiana', 'Gorditas', 'Diplomata', 'Romanesco', 'Stick', 'Almendra SC', 'Varta', 'Diplomata SC', 'Benne', 'ZCOOL KuaiLe', 'MedievalSharp', 'Revalia', 'Glass Antiqua', 'Libre Barcode 128 Text', 'Asset', 'Smythe', 'Peddana', 'Poor Story', 'Bigelow Rules', 'WindSong', 'Sedgwick Ave Display', 'Miss Fajardose', 'Macondo', 'Lexend Mega', 'Snippet', 'Qahiri', 'Londrina Sketch', 'Princess Sofia', 'Gupter', 'Syne Mono', 'Dr Sugiyama', 'Odor Mean Chey', 'Kirang Haerang', 'Irish Grover', 'Grenze', 'Mr Bedfort', 'Plaster', 'Nova Slim', 'Jacques Francois Shadow', 'Siemreap', 'Underdog', 'Freehand', 'Libre Barcode 39 Extended', 'Emblema One', 'Chela One', 'GFS Neohellenic', 'IM Fell Great Primer SC', 'Smokum', 'Dangrek', 'Long Cang', 'Unlock', 'Bokor', 'Oldenburg', 'Metal', 'Combo', 'Keania One', 'Gowun Dodum', 'Galindo', 'Kumar One Outline', 'Jacques Francois', 'Lexend Giga', 'Fascinate Inline', 'Texturina', 'Inria Sans', 'Andika New Basic', 'Taprom', 'Almendra Display', 'Brygada 1918', 'Chenla', 'Purple Purse', 'Federant', 'Liu Jian Mao Cao', 'Tourney', 'Trochut', 'Bungee Outline', 'Akaya Telivigala', 'Preahvihear', 'Big Shoulders Stencil Text', 'Zhi Mang Xing', 'Fascinate', 'Gowun Batang', 'Akaya Kanadaka', 'Supermercado One', 'IM Fell Double Pica SC', 'Butterfly Kids', 'Snowburst One', 'Stalinist One', 'Viaoda Libre', 'Suravaram', 'Orelega One', 'Erica One', 'Gidugu', 'New Tegomin', 'Nova Script', 'Nova Cut', 'Black And White Picture', 'Passero One', 'Bungee Hairline', 'Seymour One', 'Sunshiney', 'Ruge Boogie', 'Yomogi', 'Astloch', 'Sevillana', 'Bonbon', 'Nova Oval', 'Nerko One', 'Zen Tokyo Zoo', 'Miltonian', 'Sofadi One', 'Miltonian Tattoo', 'Suwannaphum', 'Big Shoulders Stencil Display', 'Vibes', 'Moulpali', 'Aubrey', 'Lexend Tera', 'Butcherman', 'Lacquer', 'STIX Two Math', 'Single Day', 'Fasthand', 'Dhurjati', 'Fuggles', 'BioRhyme Expanded', 'Hanalei', 'Ballet', 'Fruktur', 'Encode Sans SC', 'Lexend Peta', 'Truculenta', 'Kenia', 'Warnes', 'Big Shoulders Inline Text', 'Trispace', 'Bona Nova', 'Xanh Mono', 'Festive', 'Zen Loop', 'Geostar Fill', 'Imbue', 'Langar', 'Geostar', 'Karantina', 'Big Shoulders Inline Display', 'Oi', 'Syne Tactile', 'Libre Barcode EAN13 Text', 'Uchen'];

export const hasFontBeenRendered = {};

export const fontsToData = {
    'Cousine for Powerline': null,
    'Arial': null,
    'Academy Engraved LET': null,
    'Helvetica': null,
    'Verdana': null,
    'Roboto Mono Medium for Powerline': null,
    'Ubuntu Mono derivative Powerline': null,
    'Optima': null,
    'Chalkduster': null,
    'Chalkboard SE': null,
    'Bodoni 72 Oldstyle': null,
    'Avenir Next Condensed': null,
    'NovaMono for Powerline': null,
    'Helvetica Neue': null,
    'monofur for Powerline': null,
    'Droid Sans Mono Slashed for Powerline': null,
    'Arial Narrow': null,
    'Monaco': null,
    'Meslo LG L for Powerline': null,
    'Inconsolate-g for Powerline': null,
    'Gill Sans': null,
    'Noteworthy': null,
    'Roboto Mono Thin for Powerline': null,
    'Courier New': null,
    'Marker Felt': null,
    'Hack': null,
    'Skia': null,
    'Space Mono for Powerline': null,
    'Impact': null,
    'ProFont for Powerline': null,
    'Snell Roundhand': null,
    'Bodoni 72 Smallcaps': null,
    'Arial Black': null,
    'Meslo LG L DZ for Powerline': null,
    'Roboto Mono Light for Powerline': null,
    'Palatino': null,
    'Didot': null,
    'Source Code Pro for Powerline': null,
    'Meslo LG M for Powerline': null,
    'Hoefler Text': null,
    'Meslo LG M DZ for Powerline': null,
    'Tinos for Powerline': null,
    'Cochin': null,
    'Noto Mono for Powerline': null,
    'Bodoni 72': null,
    'Zapfino': null,
    'Lucida Grande': null,
    'Droid Sans Mono Dotted for Powerline': null,
    'Big Caslon': null,
    'David': null,
    'Times': null,
    'DIN Condensed': null,
    'Symbol Neu for Powerline': null,
    'Go Mono for Powerline': null,
    'Herculanum': null,
    'DIN Alternate': null,
    'Trebuchet MS': null,
    'Inconsolate for Powerline': null,
    'Droid Sans Mono for Powerline': null,
    'Inconsolate-dz for Powerline': null,
    'Garamond': null,
    'Roboto Mono for Powerline': null,
    'Courier': null,
    'Brush Script MT': null,
    'SignPainter': null,
    'IBM 3270 Narrow': null,
    'Georgia': null,
    'American Typewriter': null,
    'DejaVu Sans Mono for Powerline': null,
    'Anonymous Pro for Powerline': null,
    'Phosphate': null,
    'IBM 3270': null,
    'Charter': null,
    'IBM 3270 Semi-Narrow': null,
    'Tahoma': null,
    'Copperplate': null,
    'Party LET': null,
    'Avenir': null,
    'Chalkboard': null,
    'Baskerville': null,
    'Luminari': null,
    'Meslo LG S DZ for Powerline': null,
    'Arial Rounded MT Bold': null,
    'Geneva': null,
    'Rockwell': null,
    'Andale Mono': null,
    'Microsoft Sans Seriff': null,
    'Avenir Next': null,
    'Arial MT': null,
    'Bradley Hand': null,
    'Timew New Roman': null,
    'Ariel Unicode MS': null,
    'Tratatello': null,
    'Papyrus': null,
    'Menlo': null,
    'Futura': null,
    'Meslo LG S for Powerline': null,
    'Comic Sans MS': null,
    'Liberation Mono for Powerline': null,
    'Savoye LET': null,
    'Fira Mono for Powerline': null,
    'mass_effect_123regular': { url: 'fonts/me123-webfont.woff', format: 'woff'},
    'Andika Regular': { url: 'https://raw.githubusercontent.com/google/fonts/main/ofl/andika/Andika-Regular.ttf', format: 'truetype'},

    // Google Fonts
    // 'Spectral': null,
    // 'Brawler': null,
    // 'Coiny': null,
    // 'Kiwi Maru': null,
    // 'Bungee': null,
    // 'Lexend Mega': null,
    // 'Odibee Sans': null,
    // 'Lustria': null,
    // 'Denk One': null,
    // 'Tajawal': null,
    // 'Caladea': null,
    // 'Josefin Sans': null,
    // 'Pridi': null,
    // 'Preahvihear': null,
    // 'IM Fell Double Pica': null,
    // 'Righteous': null,
    // 'Pacifico': null,
    // 'Gayathri': null,
    // 'Marcellus': null,
    // 'Inter': null,
    // 'Astloch': null,
    // 'Pinyon Script': null,
    // 'Joti One': null,
    // 'Sora': null,
    // 'Cormorant Infant': null,
    // 'Mitr': null,
    // 'Qahiri': null,
    // 'Permanent Marker': null,
    // 'Bree Serif': null,
    // 'Athiti': null,
    // 'Monda': null,
    // 'Butcherman': null,
    // 'Trocchi': null,
    // 'Marko One': null,
    // 'Mulish': null,
    // 'Abril Fatface': null,
    // 'Marck Script': null,
    // 'Noto Serif': null,
    // 'Iceberg': null,
    // 'Merienda': null,
    // 'Modern Antiqua': null,
    // 'Baskervville': null,
    // 'Nobile': null,
    // 'Vibes': null,
    // 'Style Script': null,
    // 'B612': null,
    // 'Salsa': null,
    // 'Mountains of Christmas': null,
    // 'IM Fell English SC': null,
    // 'Signika Negative': null,
    // 'Fugaz One': null,
    // 'Trochut': null,
    // 'Annie Use Your Telescope': null,
    // 'Grenze Gotisch': null,
    // 'Fredoka One': null,
    // 'Do Hyeon': null,
    // 'Smythe': null,
    // 'Jaldi': null,
    // 'Cinzel Decorative': null,
    // 'Artifika': null,
    // 'Kaushan Script': null,
    // 'Aldrich': null,
    // 'Crimson Pro': null,
    // 'Great Vibes': null,
    // 'Quintessential': null,
    // 'Saira Condensed': null,
    // 'Norican': null,
    // 'Maven Pro': null,
    // 'Tillana': null,
    // 'Esteban': null,
    // 'Yomogi': null,
    // 'Oleo Script Swash Caps': null,
    // 'Kulim Park': null,
    // 'Gilda Display': null,
    // 'Dosis': null,
    // 'Hachi Maru Pop': null,
    // 'Calistoga': null,
    // 'Rasa': null,
    // 'Wallpoet': null,
    // 'Inder': null,
    // 'Ewert': null,
    // 'Gowun Batang': null,
    // 'STIX Two Text': null,
    // 'Buda': null,
    // 'Noto Sans JP': null,
    // 'Kelly Slab': null,
    // 'Jockey One': null,
    // 'Unkempt': null,
    // 'Akaya Telivigala': null,
    // 'Hahmlet': null,
    // 'Scada': null,
    // 'Baumans': null,
    // 'Sarabun': null,
    // 'Uncial Antiqua': null,
    // 'Noto Serif SC': null,
    // 'Notable': null,
    // 'Coustard': null,
    // 'Rouge Script': null,
    // 'Maiden Orange': null,
    // 'Varela Round': null,
    // 'Nixie One': null,
    // 'Aladin': null,
    // 'La Belle Aurore': null,
    // 'Sansita Swashed': null,
    // 'Barlow': null,
    // 'Vollkorn': null,
    // 'Chela One': null,
    // 'Bubbler One': null,
    // 'Headland One': null,
    // 'Adamina': null,
    // 'Mada': null,
    // 'Libre Franklin': null,
    // 'Black Han Sans': null,
    // 'Pavanam': null,
    // 'Eagle Lake': null,
    // 'Tomorrow': null,
    // 'Gravitas One': null,
    // 'Chivo': null,
    // 'Gloria Hallelujah': null,
    // 'Sulphur Point': null,
    // 'Anonymous Pro': null,
    // 'Yesteryear': null,
    // 'Seymour One': null,
    // 'Warnes': null,
    // 'Overpass': null,
    // 'Petrona': null,
    // 'Prompt': null,
    // 'Syne Mono': null,
    // 'DM Sans': null,
    // 'Mirza': null,
    // 'Della Respira': null,
    // 'Palanquin': null,
    // 'Courier Prime': null,
    // 'Zilla Slab Highlight': null,
    // 'Macondo Swash Caps': null,
    // 'Ruslan Display': null,
    // 'Averia Libre': null,
    // 'Fauna One': null,
    // 'Elsie': null,
    // 'Big Shoulders Inline Text': null,
    // 'Krub': null,
    // 'Cutive': null,
    // 'Cormorant Upright': null,
    // 'Sail': null,
    // 'Dokdo': null,
    // 'Sniglet': null,
    // 'Black And White Picture': null,
    // 'Cantata One': null,
    // 'Amaranth': null,
    // 'UnifrakturMaguntia': null,
    // 'Yellowtail': null,
    // 'Lexend Giga': null,
    // 'Sarina': null,
    // 'Basic': null,
    // 'Squada One': null,
    // 'Parisienne': null,
    // 'Monsieur La Doulaise': null,
    // 'Syncopate': null,
    // 'Crafty Girls': null,
    // 'Amarante': null,
    // 'Nova Slim': null,
    // 'Bahianita': null,
    // 'Big Shoulders Display': null,
    // 'Asar': null,
    // 'Eczar': null,
    // 'El Messiri': null,
    // 'Cormorant Garamond': null,
    // 'Alegreya': null,
    // 'Scheherazade': null,
    // 'Noto Serif JP': null,
    // 'Julius Sans One': null,
    // 'Antic Didone': null,
    // 'Habibi': null,
    // 'Girassol': null,
    // 'Bubblegum Sans': null,
    // 'Boogaloo': null,
    // 'Wire One': null,
    // 'Playball': null,
    // 'Sahitya': null,
    // 'Merriweather Sans': null,
    // 'Rambla': null,
    // 'Meie Script': null,
    // 'Playfair Display SC': null,
    // 'Arbutus Slab': null,
    // 'Fahkwang': null,
    // 'Lusitana': null,
    // 'Hepta Slab': null,
    // 'Bungee Inline': null,
    // 'Francois One': null,
    // 'Kameron': null,
    // 'Convergence': null,
    // 'Leckerli One': null,
    // 'Contrail One': null,
    // 'Niramit': null,
    // 'Quattrocento': null,
    // 'Gentium Book Basic': null,
    // 'Megrim': null,
    // 'PT Serif Caption': null,
    // 'Carrois Gothic': null,
    // 'Delius Unicase': null,
    // 'Poppins': null,
    // 'NTR': null,
    // 'Odor Mean Chey': null,
    // 'Londrina Solid': null,
    // 'Mr De Haviland': null,
    // 'Fascinate Inline': null,
    // 'IM Fell Great Primer SC': null,
    // 'Shanti': null,
    // 'Archivo': null,
    // 'Copse': null,
    // 'Patrick Hand': null,
    // 'Zen Tokyo Zoo': null,
    // 'Geostar Fill': null,
    // 'Syne': null,
    // 'Concert One': null,
    // 'Alatsi': null,
    // 'Six Caps': null,
    // 'Fira Mono': null,
    // 'Snippet': null,
    // 'Days One': null,
    // 'IM Fell DW Pica': null,
    // 'Grenze': null,
    // 'Rum Raisin': null,
    // 'Nokora': null,
    // 'Calligraffitti': null,
    // 'Pattaya': null,
    // 'Lora': null,
    // 'Junge': null,
    // 'Federant': null,
    // 'Halant': null,
    // 'Padauk': null,
    // 'Encode Sans Condensed': null,
    // 'McLaren': null,
    // 'Karantina': null,
    // 'Secular One': null,
    // 'Moul': null,
    // 'Expletus Sans': null,
    // 'Unna': null,
    // 'Mandali': null,
    // 'Herr Von Muellerhoff': null,
    // 'Lekton': null,
    // 'Balthazar': null,
    // 'Neuton': null,
    // 'Encode Sans Semi Condensed': null,
    // 'Nothing You Could Do': null,
    // 'Amiri': null,
    // 'Imprima': null,
    // 'Nanum Gothic Coding': null,
    // 'Cormorant': null,
    // 'Passion One': null,
    // 'Average': null,
    // 'East Sea Dokdo': null,
    // 'Bungee Outline': null,
    // 'Kosugi': null,
    // 'PT Sans': null,
    // 'Tenali Ramakrishna': null,
    // 'VT323': null,
    // 'Freehand': null,
    // 'Sree Krushnadevaraya': null,
    // 'Bitter': null,
    // 'Questrial': null,
    // 'Libre Baskerville': null,
    // 'Baloo Tamma 2': null,
    // 'Vesper Libre': null,
    // 'Barlow Condensed': null,
    // 'Proza Libre': null,
    // 'Fraunces': null,
    // 'Glegoo': null,
    // 'Unlock': null,
    // 'Sedgwick Ave': null,
    // 'Zilla Slab': null,
    // 'Dangrek': null,
    // 'Margarine': null,
    // 'Pathway Gothic One': null,
    // 'Dekko': null,
    // 'Aref Ruqaa': null,
    // 'Shadows Into Light Two': null,
    // 'Hind Vadodara': null,
    // 'Gabriela': null,
    // 'Just Me Again Down Here': null,
    // 'Julee': null,
    // 'Poor Story': null,
    // 'Bellota Text': null,
    // 'Koulen': null,
    // 'Beth Ellen': null,
    // 'Cambo': null,
    // 'Literata': null,
    // 'Inika': null,
    // 'Syne Tactile': null,
    // 'Libre Barcode 128': null,
    // 'Otomanopee One': null,
    // 'Miltonian Tattoo': null,
    // 'Kite One': null,
    // 'IBM Plex Serif': null,
    // 'Alex Brush': null,
    // 'Catamaran': null,
    // 'Kumbh Sans': null,
    // 'Kosugi Maru': null,
    // 'Pragati Narrow': null,
    // 'Big Shoulders Stencil Text': null,
    // 'Mrs Saint Delafield': null,
    // 'Titillium Web': null,
    // 'Nova Oval': null,
    // 'Tangerine': null,
    // 'IM Fell Great Primer': null,
    // 'Libre Barcode 39 Extended Text': null,
    // 'Fruktur': null,
    // 'Pompiere': null,
    // 'Flavors': null,
    // 'Finger Paint': null,
    // 'Sansita': null,
    // 'Carme': null,
    // 'Martel Sans': null,
    // 'Jura': null,
    // 'Keania One': null,
    // 'GFS Didot': null,
    // 'Cardo': null,
    // 'Space Grotesk': null,
    // 'Kreon': null,
    // 'Libre Barcode EAN13 Text': null,
    // 'Caveat Brush': null,
    // 'Exo 2': null,
    // 'Germania One': null,
    // 'Kodchasan': null,
    // 'Nosifer': null,
    // 'Mr Dafoe': null,
    // 'Bai Jamjuree': null,
    // 'Noticia Text': null,
    // 'Almendra Display': null,
    // 'Asap Condensed': null,
    // 'Gudea': null,
    // 'Devonshire': null,
    // 'Press Start 2P': null,
    // 'Oxygen Mono': null,
    // 'Rosarivo': null,
    // 'Suwannaphum': null,
    // 'Cairo': null,
    // 'Spicy Rice': null,
    // 'Poller One': null,
    // 'Voces': null,
    // 'Poly': null,
    // 'Harmattan': null,
    // 'Chonburi': null,
    // 'Moulpali': null,
    // 'Rokkitt': null,
    // 'Oswald': null,
    // 'Abel': null,
    // 'Didact Gothic': null,
    // 'Arima Madurai': null,
    // 'Bangers': null,
    // 'Dorsa': null,
    // 'BenchNine': null,
    // 'Sirin Stencil': null,
    // 'ABeeZee': null,
    // 'Combo': null,
    // 'Encode Sans Expanded': null,
    // 'Mukta': null,
    // 'Loved by the King': null,
    // 'Encode Sans Semi Expanded': null,
    // 'Tenor Sans': null,
    // 'Bowlby One SC': null,
    // 'Meddon': null,
    // 'Katibeh': null,
    // 'Bahiana': null,
    // 'Luckiest Guy': null,
    // 'Martel': null,
    // 'Tinos': null,
    // 'Blinker': null,
    // 'Mr Bedfort': null,
    // 'Aubrey': null,
    // 'Festive': null,
    // 'Ovo': null,
    // 'Eater': null,
    // 'BioRhyme': null,
    // 'Bodoni Moda': null,
    // 'Liu Jian Mao Cao': null,
    // 'Mate SC': null,
    // 'Port Lligat Slab': null,
    // 'GFS Neohellenic': null,
    // 'Cantora One': null,
    // 'Dr Sugiyama': null,
    // 'Metamorphous': null,
    // 'Miniver': null,
    // 'Ibarra Real Nova': null,
    // 'Nova Flat': null,
    // 'Yeseva One': null,
    // 'Tienne': null,
    // 'Red Hat Text': null,
    // 'Metal': null,
    // 'Gochi Hand': null,
    // 'Inria Sans': null,
    // 'Modak': null,
    // 'ZCOOL QingKe HuangYou': null,
    // 'Gaegu': null,
    // 'Felipa': null,
    // 'Mali': null,
    // 'Peddana': null,
    // 'Cormorant SC': null,
    // 'Noto Sans TC': null,
    // 'Stint Ultra Condensed': null,
    // 'Major Mono Display': null,
    // 'Fenix': null,
    // 'Hanuman': null,
    // 'Puritan': null,
    // 'Zen Dots': null,
    // 'Shrikhand': null,
    // 'Cutive Mono': null,
    // 'Arsenal': null,
    // 'Bellefair': null,
    // 'Barlow Semi Condensed': null,
    // 'M PLUS 1p': null,
    // 'Nova Mono': null,
    // 'Lilita One': null,
    // 'Baloo Paaji 2': null,
    // 'Georama': null,
    // 'Suez One': null,
    // 'Numans': null,
    // 'Handlee': null,
    // 'Schoolbell': null,
    // 'Baloo Bhai 2': null,
    // 'Varta': null,
    // 'Old Standard TT': null,
    // 'Rancho': null,
    // 'Paytone One': null,
    // 'Short Stack': null,
    // 'Happy Monkey': null,
    // 'Michroma': null,
    // 'Duru Sans': null,
    // 'Ruda': null,
    // 'Arya': null,
    // 'Amatic SC': null,
    // 'Coda Caption': null,
    // 'Lily Script One': null,
    // 'Marmelad': null,
    // 'STIX Two Math': null,
    // 'Crushed': null,
    // 'Libre Barcode 39 Text': null,
    // 'Work Sans': null,
    // 'Roboto Slab': null,
    // 'Langar': null,
    // 'Emblema One': null,
    // 'Battambang': null,
    // 'Montserrat Subrayada': null,
    // 'Racing Sans One': null,
    // 'Barrio': null,
    // 'Taviraj': null,
    // 'Open Sans Condensed': null,
    // 'Andika New Basic': null,
    // 'Gidugu': null,
    // 'Farsan': null,
    // 'Song Myung': null,
    // 'Black Ops One': null,
    // 'Libre Caslon Text': null,
    // 'Qwigley': null,
    // 'Ropa Sans': null,
    // 'Stylish': null,
    // 'Butterfly Kids': null,
    // 'MuseoModerno': null,
    // 'Almendra': null,
    // 'Almendra SC': null,
    // 'Rufina': null,
    // 'Milonga': null,
    // 'Markazi Text': null,
    // 'Alegreya Sans': null,
    // 'Coda': null,
    // 'Viaoda Libre': null,
    // 'Gowun Dodum': null,
    // 'Bentham': null,
    // 'Hind Guntur': null,
    // 'Sedgwick Ave Display': null,
    // 'Andada': null,
    // 'Supermercado One': null,
    // 'Reem Kufi': null,
    // 'Hanalei Fill': null,
    // 'Sen': null,
    // 'Ultra': null,
    // 'Sonsie One': null,
    // 'Encode Sans SC': null,
    // 'Long Cang': null,
    // 'Oldenburg': null,
    // 'Swanky and Moo Moo': null,
    // 'Lalezar': null,
    // 'Sevillana': null,
    // 'Sofadi One': null,
    // 'Fjalla One': null,
    // 'Wellfleet': null,
    // 'Indie Flower': null,
    // 'Gupter': null,
    // 'Nova Script': null,
    // 'Architects Daughter': null,
    // 'BioRhyme Expanded': null,
    // 'Podkova': null,
    // 'Dynalight': null,
    // 'Fanwood Text': null,
    // 'Lato': null,
    // 'Berkshire Swash': null,
    // 'Capriola': null,
    // 'Quantico': null,
    // 'Grandstander': null,
    // 'Goudy Bookletter 1911': null,
    // 'Iceland': null,
    // 'Archivo Black': null,
    // 'Russo One': null,
    // 'Meera Inimai': null,
    // 'MonteCarlo': null,
    // 'Hammersmith One': null,
    // 'Angkor': null,
    // 'Faustina': null,
    // 'Yeon Sung': null,
    // 'Offside': null,
    // 'K2D': null,
    // 'Cagliostro': null,
    // 'Walter Turncoat': null,
    // 'Give You Glory': null,
    // 'Siemreap': null,
    // 'Alike Angular': null,
    // 'Fjord One': null,
    // 'Montserrat': null,
    // 'Gurajada': null,
    // 'Lexend Peta': null,
    // 'Text Me One': null,
    // 'Gorditas': null,
    // 'Libre Caslon Display': null,
    // 'Candal': null,
    // 'Lancelot': null,
    // 'DM Mono': null,
    // 'Vampiro One': null,
    // 'Sriracha': null,
    // 'Domine': null,
    // 'Glass Antiqua': null,
    // 'Kumar One Outline': null,
    // 'Ballet': null,
    // 'Charmonman': null,
    // 'Sofia': null,
    // 'DM Serif Display': null,
    // 'Dancing Script': null,
    // 'IM Fell Double Pica SC': null,
    // 'Share Tech': null,
    // 'Varela': null,
    // 'Nanum Brush Script': null,
    // 'Imbue': null,
    // 'PT Sans Caption': null,
    // 'Homemade Apple': null,
    // 'Darker Grotesque': null,
    // 'Sunflower': null,
    // 'Kalam': null,
    // 'Merriweather': null,
    // 'Karla': null,
    // 'JetBrains Mono': null,
    // 'Graduate': null,
    // 'Bilbo Swash Caps': null,
    // 'Slabo 27px': null,
    // 'Mate': null,
    // 'Zhi Mang Xing': null,
    // 'Cantarell': null,
    // 'Heebo': null,
    // 'Nunito Sans': null,
    // 'Rammetto One': null,
    // 'Cousine': null,
    // 'Forum': null,
    // 'Vibur': null,
    // 'Sarala': null,
    // 'Kufam': null,
    // 'Holtwood One SC': null,
    // 'Sacramento': null,
    // 'Jim Nightshade': null,
    // 'Big Shoulders Stencil Display': null,
    // 'EB Garamond': null,
    // 'Farro': null,
    // 'Stalinist One': null,
    // 'Nanum Gothic': null,
    // 'Jacques Francois Shadow': null,
    // 'Manrope': null,
    // 'Pontano Sans': null,
    // 'Codystar': null,
    // 'Engagement': null,
    // 'Sintony': null,
    // 'Carrois Gothic SC': null,
    // 'Diplomata SC': null,
    // 'Bonbon': null,
    // 'Kirang Haerang': null,
    // 'Italiana': null,
    // 'Ramabhadra': null,
    // 'Lexend Exa': null,
    // 'Original Surfer': null,
    // 'Hind Madurai': null,
    // 'Cinzel': null,
    // 'Grand Hotel': null,
    // 'Abhaya Libre': null,
    // 'Aclonica': null,
    // 'Shojumaru': null,
    // 'Bevan': null,
    // 'Creepster': null,
    // 'Unica One': null,
    // 'Underdog': null,
    // 'Manjari': null,
    // 'Donegal One': null,
    // 'Jomolhari': null,
    // 'IM Fell DW Pica SC': null,
    // 'Lobster': null,
    // 'Alike': null,
    // 'Galindo': null,
    // 'Faster One': null,
    // 'Arapey': null,
    // 'Averia Gruesa Libre': null,
    // 'Encode Sans': null,
    // 'Kdam Thmor': null,
    // 'Kumar One': null,
    // 'Rochester': null,
    // 'Recursive': null,
    // 'Chathura': null,
    // 'PT Sans Narrow': null,
    // 'Gruppo': null,
    // 'Miltonian': null,
    // 'Bigelow Rules': null,
    // 'Be Vietnam': null,
    // 'Allan': null,
    // 'Risque': null,
    // 'Ravi Prakash': null,
    // 'Lexend': null,
    // 'Emilys Candy': null,
    // 'Elsie Swash Caps': null,
    // 'Allerta': null,
    // 'Noto Sans SC': null,
    // 'Marcellus SC': null,
    // 'Satisfy': null,
    // 'Sawarabi Gothic': null,
    // 'Sancreek': null,
    // 'Clicker Script': null,
    // 'Mukta Mahee': null,
    // 'Monofett': null,
    // 'Griffy': null,
    // 'Baloo Thambi 2': null,
    // 'Port Lligat Sans': null,
    // 'Train One': null,
    // 'Libre Barcode 128 Text': null,
    // 'Sawarabi Mincho': null,
    // 'Londrina Outline': null,
    // 'Manuale': null,
    // 'Montserrat Alternates': null,
    // 'Itim': null,
    // 'Acme': null,
    // 'Exo': null,
    // 'Telex': null,
    // 'Piazzolla': null,
    // 'Macondo': null,
    // 'Orienta': null,
    // 'Mukta Vaani': null,
    // 'Judson': null,
    // 'Roboto Mono': null,
    // 'Overlock SC': null,
    // 'Redressed': null,
    // 'Ubuntu Mono': null,
    // 'Sunshiney': null,
    // 'DotGothic16': null,
    // 'Andika': null,
    // 'Over the Rainbow': null,
    // 'Scope One': null,
    // 'Single Day': null,
    // 'Strait': null,
    // 'Oranienbaum': null,
    // 'Chau Philomene One': null,
    // 'Castoro': null,
    // 'Henny Penny': null,
    // 'Wendy One': null,
    // 'Allura': null,
    // 'Londrina Shadow': null,
    // 'Prociono': null,
    // 'Fira Sans Extra Condensed': null,
    // 'Lexend Tera': null,
    // 'Limelight': null,
    // 'Chilanka': null,
    // 'Nunito': null,
    // 'Cuprum': null,
    // 'Merienda One': null,
    // 'Bayon': null,
    // 'Gamja Flower': null,
    // 'Voltaire': null,
    // 'Lateef': null,
    // 'Linden Hill': null,
    // 'Noto Sans HK': null,
    // 'Purple Purse': null,
    // 'Khula': null,
    // 'Livvic': null,
    // 'Kanit': null,
    // 'Reggae One': null,
    // 'Cabin': null,
    // 'Corben': null,
    // 'Play': null,
    // 'Jua': null,
    // 'Nova Cut': null,
    // 'Sura': null,
    // 'Romanesco': null,
    // 'Stoke': null,
    // 'Plaster': null,
    // 'Hanalei': null,
    // 'Yrsa': null,
    // 'Lakki Reddy': null,
    // 'News Cycle': null,
    // 'Saira Semi Condensed': null,
    // 'Knewave': null,
    // 'Stick': null,
    // 'Anton': null,
    // 'Lexend Deca': null,
    // 'Reenie Beanie': null,
    // 'Baloo Tammudu 2': null,
    // 'Geo': null,
    // 'Atma': null,
    // 'Ramaraja': null,
    // 'Arbutus': null,
    // 'Alegreya SC': null,
    // 'Antic': null,
    // 'Khand': null,
    // 'Ma Shan Zheng': null,
    // 'Molengo': null,
    // 'Prosto One': null,
    // 'Anaheim': null,
    // 'Hi Melody': null,
    // 'Londrina Sketch': null,
    // 'Baloo Da 2': null,
    // 'Ribeye Marrow': null,
    // 'Titan One': null,
    // 'Neucha': null,
    // 'Thasadith': null,
    // 'ZCOOL XiaoWei': null,
    // 'Smokum': null,
    // 'Audiowide': null,
    // 'Bungee Hairline': null,
    // 'Trirong': null,
    // 'Red Rose': null,
    // 'Monoton': null,
    // 'Arizonia': null,
    // 'Brygada 1918': null,
    // 'Fasthand': null,
    // 'The Girl Next Door': null,
    // 'Jolly Lodger': null,
    // 'Cormorant Unicase': null,
    // 'Dhurjati': null,
    // 'Lobster Two': null,
    // 'Saira Extra Condensed': null,
    // 'Libre Barcode 39': null,
    // 'Trade Winds': null,
    // 'Armata': null,
    // 'Kenia': null,
    // 'Hind': null,
    // 'Kavivanar': null,
    // 'Piedra': null,
    // 'Content': null,
    // 'MedievalSharp': null,
    // 'PT Serif': null,
    // 'Fontdiner Swanky': null,
    // 'Rozha One': null,
    // 'Rubik': null,
    // 'Uchen': null,
    // 'Spirax': null,
    // 'Jacques Francois': null,
    // 'Lovers Quarrel': null,
    // 'Sarpanch': null,
    // 'Taprom': null,
    // 'Fredericka the Great': null,
    // 'Saira Stencil One': null,
    // 'Delius Swash Caps': null,
    // 'Oi': null,
    // 'Prata': null,
    // 'Pangolin': null,
    // 'Shadows Into Light': null,
    // 'Lexend Zetta': null,
    // 'Gafata': null,
    // 'Chenla': null,
    // 'Medula One': null,
    // 'Chicle': null,
    // 'Charm': null,
    // 'Belgrano': null,
    // 'Gentium Basic': null,
    // 'Galdeano': null,
    // 'Overlock': null,
    // 'Advent Pro': null,
    // 'Zen Loop': null,
    // 'Kurale': null,
    // 'Electrolize': null,
    // 'Oxygen': null,
    // 'Averia Serif Libre': null,
    // 'Big Shoulders Text': null,
    // 'Peralta': null,
    // 'Benne': null,
    // 'Covered By Your Grace': null,
    // 'Commissioner': null,
    // 'Vast Shadow': null,
    // 'Homenaje': null,
    // 'Trykker': null,
    // 'Bigshot One': null,
    // 'Caveat': null,
    // 'Suranna': null,
    // 'Bad Script': null,
    // 'Freckle Face': null,
    // 'Mansalva': null,
    // 'Vollkorn SC': null,
    // 'Inria Serif': null,
    // 'Miriam Libre': null,
    // 'Metal Mania': null,
    // 'Truculenta': null,
    // 'Mina': null,
    // 'Roboto Condensed': null,
    // 'Bungee Shade': null,
    // 'Kadwa': null,
    // 'Diplomata': null,
    // 'Goldman': null,
    // 'Baloo Bhaina 2': null,
    // 'Rowdies': null,
    // 'Amethysta': null,
    // 'Fira Sans': null,
    // 'Crete Round': null,
    // 'Sigmar One': null,
    // 'Arvo': null,
    // 'IM Fell French Canon SC': null,
    // 'Montez': null,
    // 'Chakra Petch': null,
    // 'UnifrakturCook': null,
    // 'Rhodium Libre': null,
    // 'Seaweed Script': null,
    // 'Tauri': null,
    // 'Rajdhani': null,
    // 'League Script': null,
    // 'Kantumruy': null,
    // 'Stalemate': null,
    // 'Andada Pro': null,
    // 'Xanh Mono': null,
    // 'IBM Plex Sans Condensed': null,
    // 'Rosario': null,
    // 'Sue Ellen Francisco': null,
    // 'Jomhuria': null,
    // 'Love Ya Like A Sister': null,
    // 'Doppio One': null,
    // 'Mrs Sheppards': null,
    // 'Condiment': null,
    // 'Roboto': null,
    // 'Amita': null,
    // 'Chango': null,
    // 'Frank Ruhl Libre': null,
    // 'Quicksand': null,
    // 'Barriecito': null,
    // 'Bona Nova': null,
    // 'Changa': null,
    // 'Signika': null,
    // 'Epilogue': null,
    // 'Suravaram': null,
    // 'Galada': null,
    // 'Geostar': null,
    // 'Palette Mosaic': null,
    // 'Source Sans Pro': null,
    // 'Asul': null,
    // 'Nanum Pen Script': null,
    // 'Teko': null,
    // 'Nerko One': null,
    // 'Alice': null,
    // 'Ledger': null,
    // 'Princess Sofia': null,
    // 'Quattrocento Sans': null,
    // 'Patrick Hand SC': null,
    // 'Slabo 13px': null,
    // 'Courgette': null,
    // 'Damion': null,
    // 'Viga': null,
    // 'Carter One': null,
    // 'Inknut Antiqua': null,
    // 'Cambay': null,
    // 'Enriqueta': null,
    // 'Oleo Script': null,
    // 'Yusei Magic': null,
    // 'Bokor': null,
    // 'Share': null,
    // 'Space Mono': null,
    // 'Inconsolata': null,
    // 'Antic Slab': null,
    // 'Irish Grover': null,
    // 'Molle': null,
    // 'Alata': null,
    // 'IM Fell English': null,
    // 'Alfa Slab One': null,
    // 'Erica One': null,
    // 'Belleza': null,
    // 'Simonetta': null,
    // 'Passero One': null,
    // 'Lemon': null,
    // 'Sorts Mill Goudy': null,
    // 'Aguafina Script': null,
    // 'David Libre': null,
    // 'Yantramanav': null,
    // 'Raleway': null,
    // 'Pirata One': null,
    // 'Actor': null,
    // 'Stardos Stencil': null,
    // 'Mallanna': null,
    // 'Chewy': null,
    // 'Oxanium': null,
    // 'Orbitron': null,
    // 'Palanquin Dark': null,
    // 'Nova Square': null,
    // 'Balsamiq Sans': null,
    // 'Skranji': null,
    // 'Allerta Stencil': null,
    // 'Public Sans': null,
    // 'New Rocker': null,
    // 'Archivo Narrow': null,
    // 'Lacquer': null,
    // 'Tulpen One': null,
    // 'Fuggles': null,
    // 'Quando': null,
    // 'Hind Siliguri': null,
    // 'Fondamento': null,
    // 'Open Sans': null,
    // 'Raleway Dots': null,
    // 'Ubuntu Condensed': null,
    // 'Yatra One': null,
    // 'Caudex': null,
    // 'Potta One': null,
    // 'Ceviche One': null,
    // 'Averia Sans Libre': null,
    // 'Sumana': null,
    // 'Poiret One': null,
    // 'Source Code Pro': null,
    // 'Fascinate': null,
    // 'Changa One': null,
    // 'Texturina': null,
    // 'Montaga': null,
    // 'Khmer': null,
    // 'Baloo 2': null,
    // 'Antonio': null,
    // 'Noto Sans KR': null,
    // 'Maitree': null,
    // 'Karma': null,
    // 'Ranga': null,
    // 'Euphoria Script': null,
    // 'Economica': null,
    // 'DM Serif Text': null,
    // 'PT Mono': null,
    // 'Snowburst One': null,
    // 'Sanchez': null,
    // 'Metrophobic': null,
    // 'Cabin Sketch': null,
    // 'Bilbo': null,
    // 'Revalia': null,
    // 'Asap': null,
    // 'Turret Road': null,
    // 'Just Another Hand': null,
    // 'Volkhov': null,
    // 'Rock Salt': null,
    // 'Bellota': null,
    // 'Noto Sans': null,
    // 'Mako': null,
    // 'Englebert': null,
    // 'IBM Plex Sans': null,
    // 'Bowlby One': null,
    // 'Amiko': null,
    // 'Gelasio': null,
    // 'Gotu': null,
    // 'Staatliches': null,
    // 'Shippori Mincho B1': null,
    // 'Kristi': null,
    // 'Average Sans': null,
    // 'Asset': null,
    // 'Cedarville Cursive': null,
    // 'Fresca': null,
    // 'Arimo': null,
    // 'ZCOOL KuaiLe': null,
    // 'Mystery Quest': null,
    // 'Assistant': null,
    // 'Crimson Text': null,
    // 'Kavoon': null,
    // 'Rakkas': null,
    // 'Cookie': null,
    // 'Ubuntu': null,
    // 'Patua One': null,
    // 'Kranky': null,
    // 'Solway': null,
    // 'Mouse Memoirs': null,
    // 'Ruthie': null,
    // 'WindSong': null,
    // 'Big Shoulders Inline Display': null,
    // 'Yanull Kaffeesatz': null,
    // 'Libre Barcode 39 Extended': null,
    // 'Niconne': null,
    // 'Istok Web': null,
    // 'Akaya Kanadaka': null,
    // 'Slackey': null,
    // 'Comic Neue': null,
    // 'Trispace': null,
    // 'Josefin Slab': null,
    // 'Tourney': null,
    // 'Buenard': null,
    // 'Marvel': null,
    // 'Spinnaker': null,
    // 'IM Fell French Canon': null,
    // 'Ranchers': null,
    // 'Shippori Mincho': null,
    // 'Frijole': null,
    // 'Radley': null,
    // 'Kotta One': null,
    // 'Bebas Neue': null,
    // 'Noto Serif KR': null,
    // 'Chelsea Market': null,
    // 'Gugi': null,
    // 'Goblin One': null,
    // 'Orelega One': null,
    // 'Overpass Mono': null,
    // 'Croissant One': null,
    // 'Autour One': null,
    // 'Alegreya Sans SC': null,
    // 'Special Elite': null,
    // 'Ruluko': null,
    // 'Share Tech Mono': null,
    // 'Mogra': null,
    // 'Rye': null,
    // 'KoHo': null,
    // 'Philosopher': null,
    // 'Jost': null,
    // 'Gothic A1': null,
    // 'Newsreader': null,
    // 'Red Hat Display': null,
    // 'Nova Round': null,
    // 'Biryani': null,
    // 'Akronim': null,
    // 'Cabin Condensed': null,
    // 'Fira Sans Condensed': null,
    // 'Zeyada': null,
    // 'Lemonada': null,
    // 'Cherry Swash': null,
    // 'Mukta Malar': null,
    // 'Source Serif Pro': null,
    // 'Playfair Display': null,
    // 'Magra': null,
    // 'Stint Ultra Expanded': null,
    // 'Rubik Mono One': null,
    // 'Timmana': null,
    // 'Spartan': null,
    // 'IBM Plex Mono': null,
    // 'New Tegomin': null,
    // 'Srisakdi': null,
    // 'Caesar Dressing': null,
    // 'Nanum Myeongjo': null,
    // 'Rationale': null,
    // 'Almarai': null,
    // 'Baloo Chettan 2': null,
    // 'Miss Fajardose': null,
    // 'Vidaloka': null,
    // 'Laila': null,
    // 'Saira': null,
    // 'Ruge Boogie': null,
    // 'Dawning of a New Day': null,
    // 'M PLUS Rounded 1c': null,
    // 'Fira Code': null,
    // 'B612 Mono': null,
    // 'RocknRoll One': null,
    // 'Petit Formal Script': null,
    // 'Coming Soon': null,
    // 'Aleo': null,
    // 'Italianno': null,
    // 'Dela Gothic One': null,
    // 'Life Savers': null,
    // 'Alef': null,
    // 'Paprika': null,
    // 'Cherry Cream Soda': null,
    // 'Waiting for the Sunrise': null,
    // 'Noto Serif TC': null,
    // 'Atomic Age': null,
    // 'Delius': null,
    // 'Comfortaa': null,
    // 'Federo': null,
    // 'Atkinson Hyperlegible': null,
    // 'Cute Font': null,
    // 'Ribeye': null,
    // 'Krona One': null,
    // 'Oregano': null,
    // 'Spectral SC': null,
    // 'Flamenco': null
};
